version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telecom_customer_churn
        description: "Raw telecom customer churn table loaded into schema raw or replaced by the sample seed during dev."

models:
  - name: stg_customer_churn
    description: "Stage: normalize names and types from the raw churn source"
    columns:
      - name: customer_id
        description: "Unique customer id"
        tests: [not_null, unique]
      - name: zip_code
        description: "Customer zip code"
        tests: [not_null]

  - name: stg_zipcode_population
    description: "Stage: zipcode population from seed"
    columns:
      - name: zip_code
        description: "Zip code"
        tests: [not_null, unique]
      - name: population
        description: "Population estimate"
        tests: [not_null]
